export interface CountryCode {
  name: string;
  dialCode: string;
  iso: string;
}

export const countryCodes: CountryCode[] = [
  { name: "United States", dialCode: "+1", iso: "US" },
  { name: "Canada", dialCode: "+1", iso: "CA" },
  { name: "United Kingdom", dialCode: "+44", iso: "GB" },
  { name: "India", dialCode: "+91", iso: "IN" },
  { name: "Australia", dialCode: "+61", iso: "AU" },
  { name: "Germany", dialCode: "+49", iso: "DE" },
  { name: "France", dialCode: "+33", iso: "FR" },
  { name: "Italy", dialCode: "+39", iso: "IT" },
  { name: "Spain", dialCode: "+34", iso: "ES" },
  { name: "Netherlands", dialCode: "+31", iso: "NL" },
  { name: "Belgium", dialCode: "+32", iso: "BE" },
  { name: "Switzerland", dialCode: "+41", iso: "CH" },
  { name: "Sweden", dialCode: "+46", iso: "SE" },
  { name: "Norway", dialCode: "+47", iso: "NO" },
  { name: "Denmark", dialCode: "+45", iso: "DK" },
  { name: "Finland", dialCode: "+358", iso: "FI" },
  { name: "Ireland", dialCode: "+353", iso: "IE" },
  { name: "Portugal", dialCode: "+351", iso: "PT" },
  { name: "Poland", dialCode: "+48", iso: "PL" },
  { name: "Austria", dialCode: "+43", iso: "AT" },
  { name: "Greece", dialCode: "+30", iso: "GR" },
  { name: "Russia", dialCode: "+7", iso: "RU" },
  { name: "Turkey", dialCode: "+90", iso: "TR" },
  { name: "Israel", dialCode: "+972", iso: "IL" },
  { name: "United Arab Emirates", dialCode: "+971", iso: "AE" },
  { name: "Saudi Arabia", dialCode: "+966", iso: "SA" },
  { name: "South Africa", dialCode: "+27", iso: "ZA" },
  { name: "Nigeria", dialCode: "+234", iso: "NG" },
  { name: "Egypt", dialCode: "+20", iso: "EG" },
  { name: "Kenya", dialCode: "+254", iso: "KE" },
  { name: "China", dialCode: "+86", iso: "CN" },
  { name: "Japan", dialCode: "+81", iso: "JP" },
  { name: "South Korea", dialCode: "+82", iso: "KR" },
  { name: "Singapore", dialCode: "+65", iso: "SG" },
  { name: "Malaysia", dialCode: "+60", iso: "MY" },
  { name: "Indonesia", dialCode: "+62", iso: "ID" },
  { name: "Thailand", dialCode: "+66", iso: "TH" },
  { name: "Vietnam", dialCode: "+84", iso: "VN" },
  { name: "Philippines", dialCode: "+63", iso: "PH" },
  { name: "Pakistan", dialCode: "+92", iso: "PK" },
  { name: "Bangladesh", dialCode: "+880", iso: "BD" },
  { name: "Sri Lanka", dialCode: "+94", iso: "LK" },
  { name: "Nepal", dialCode: "+977", iso: "NP" },
  { name: "New Zealand", dialCode: "+64", iso: "NZ" },
  { name: "Brazil", dialCode: "+55", iso: "BR" },
  { name: "Mexico", dialCode: "+52", iso: "MX" },
  { name: "Argentina", dialCode: "+54", iso: "AR" },
  { name: "Chile", dialCode: "+56", iso: "CL" },
  { name: "Colombia", dialCode: "+57", iso: "CO" },
  { name: "Peru", dialCode: "+51", iso: "PE" },
];
